// Make it global
window.allLanguages = {
  "Arabic": "ar",
  "Bulgarian": "bg",
  "Chinese": "zh",
  "Simplified Chinese": "zh-cn",
  "Chinese Simplified": "zh-cn",
  "Traditional Chinese": "zh-tw",
  "Croatian": "hr",
  "Czech": "cs",
  "Danish": "da",
  "Dutch": "nl",
  "English": "en",
  "Finnish": "fi",
  "French": "fr",
  "German": "de",
  "Greek": "el",
  "Hebrew": "he",
  "Hungarian": "hu",
  "Indonesian": "id",
  "Italian": "it",
  "Japanese": "ja",
  "Korean": "ko",
  "Norwegian": "no",
  "Polish": "pl",
  "Portuguese": "pt",
  "Portuguese - Brazil": "pt-br",
  "Romanian": "ro",
  "Russian": "ru",
  "Spanish": "es",
  "Spanish - Spain": "es-419",
  "Swedish": "sv",
  "Thai": "th",
  "Turkish": "tr",
  "Ukrainian": "uk",
  "Vietnamese": "vi",
  "Malay": "ms",
  "Hindi": "hi",
  "Persian": "fa",
  "Latvian": "lv",
  "Lithuanian": "lt",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Estonian": "et",
  "Catalan": "ca",
  "Spanish - Latin America": "es-latam"
};
